- name: Configure and Deploy Selenium Application on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Google Chrome (Dependency for ChromeDriver)
      ansible.builtin.apt:
        name: google-chrome-stable
        state: present
      # Ensure you have added Google's official APT repository if not already present
      # (e.g., using 'ansible.builtin.apt_repository' module in a prior task)
      # For example:
      # - name: Add Google Chrome repository
      #   ansible.builtin.apt_repository:
      #     repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
      #     state: present
      #     filename: google-chrome
      #     mode: '0644'
      #     update_cache: yes
      # - name: Import Google Chrome GPG key
      #   ansible.builtin.apt_key:
      #     url:
